apiVersion: v1
kind: Service
metadata:
  name: helloworld
  annotations:
    skupper.io/proxy: http
  labels:
    app: simplevm
spec:
  ports:
  - port: 1500
    protocol: TCP
    targetPort: 1500
  selector:
    kubevirt.io/vmReplicaSet: vmi-replicaset-fedora
