apiVersion: v1
data:
  cluster-local: "false"
  console: "false"
  console-authentication: internal
  console-password: "rubble"
  console-user: "barney"
  edge: "false"
  name: fe-site
  router-console: "false"
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site
  labels:
    app: simplevm