apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: simplevm     
  namespace: simple-vmapp  
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - vmapp 
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription